### ISSUE TITLE
frontend JS source maps are broken

### ISSUE THREAD

**Issue by johnkruger37** [dfinity/examples#102]
`dfx new first && cd first && npm install && dfx deploy`

```
Deploying all canisters.
All canisters have already been created.
Building canisters...
Building frontend...
Installing canisters...
(...)
  /index.js.map 1/1 (952215 bytes)
  /index.js.map (gzip) 1/1 (254247 bytes)
Deployed canisters.
```

http://localhost:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai

Firefox F12 Consle:

```
Source map error: Error: request failed with status 500
Resource URL: http://localhost:8000/index.js
Source Map URL: index.js.map
```

From what little I understand about this, the build did seem to produce source maps, but for some reason they're not found; not sure what's missing.

**Comment by johnkruger37** [comment]
PS: I realized this isn't strictly about the _examples_ repo, but it's not clear to me yet where else to file this - which repo has the source for what `dfx new` produces?

**Comment by fury02** [comment]
I have the same problem. Try the command **dfx canister install --all --mode reinstall** after the start. Canister problem. The front end eventually earned
