### ISSUE TITLE
ledger-transfer - step 4 -> is not opt, reserved or null

### ISSUE THREAD

**Issue by leo-web3** [dfinity/examples#125]

**Comment by leo-icp** [comment]
I follow examples 
https://github.com/dfinity/examples/tree/2096a6aba6ef25e1758ff4e5fa8e0f55146132a5/motoko/ledger-transfer
To run, a strange problem occurred in step 4

einstalling code for canister ledger, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
The invocation to the wallet call forward method failed with the error: An error happened during the call: 5: Canister rrkah-fqaaa-aaaaa-aaaaq-cai trapped explicitly: Panicked at 'Deserialization Failed: "No more values on the wire, the expected type record {\n  send_whitelist : vec principal;\n  minting_account : text;\n  transaction_window : opt record { secs : nat64; nanos : nat32 };\n  max_message_size_bytes : opt nat64;\n  archive_options : opt record {\n    num_blocks_to_archive : nat64;\n    trigger_threshold : nat64;\n    max_message_size_bytes : opt nat64;\n    node_max_memory_size_bytes : opt nat64;\n    controller_id : principal;\n  };\n  initial_values : vec record { text; record { e8s : nat64 } };\n} is not opt, reserved or null"', /Users/cory/Workspace/dfinity/ic/rs/rust_canisters/dfn_core/src/endpoint.rs:50:41

**Comment by leo-icp** [comment]
```
dfx canister install ledger --mode=reinstall --argument='(record {send_whitelist=vec{};minting_account="051b05839339f89053454a4b9865ea0452a4bffe2b1cd41f4982bad10c1e637c"; transaction_window = null; max_message_size_bytes = null; archive_options = null; initial_values = vec {record{"bdc4ee05d42cd0669786899f256c8fd7217fa71177bd1fa7b9534f568680a938"; record {e8s=100_000_000_000}}};})'
```
