### ISSUE TITLE
Unity-Webgl Example should include I/O and deploy to live cannister not just localhost 

### ISSUE THREAD

**Issue by yosun** [dfinity/examples#272]
This seems to be using just generated code from Unity WebGL default. The directions for deploying are incomplete, as it only includes localhost. A snippet should be provided on how to (minimally) POST/GET from Unity C# with a ICP server. 

https://github.com/dfinity/examples/tree/master/hosting/unity-webgl-template

**Comment by Jibin-John** [comment]
The folder structure is not well understood. I took a WebGL build from unity and compared it. Needed a better explanation for this.
