### ISSUE TITLE
Failed to run hello-world sample

### ISSUE THREAD

**Issue by dimas-prawira** [dfinity/examples#40]
Hi, I have download SDK based on instructions and testing it with command

`$dfx --version
dfx 0.6.4
`

I clone examples motoko, from github and start to run hello-world based on instructions 

1. run `$dfx start`
    `sudo dfx start
⠦ Checking replica!
Aug 28 14:52:16.142 INFO ic-starter. Configuration: ValidatedConfig { node_id: 100, replica_path: Some("/root/.cache/dfinity/versions/0.6.4/replica"), subnet_id: 0, cargo_bin: "cargo", cargo_opts: "", state_dir: "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replicated_state", http_port_config: WritePortTo("/home/dimas/motoko/examples/motoko/hello-world/.dfx/client-configuration/client-1.port"), http_require_valid_signatures: true, artifact_pool_dir: "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replicated_state/node-100/ic_consensus_pool", crypto_root: "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replicated_state/node-100/crypto", state_manager_root: "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replicated_state/node-100/state", registry_file: "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replicated_state/node-100/registry.proto", state_dir_holder: None }, Application: starter
Aug 28 14:52:16.142 INFO Executing "/root/.cache/dfinity/versions/0.6.4/replica" "/home/dimas/motoko/examples/motoko/hello-world/.dfx/state/replic⠒ Checking replica!
Aug 28 14:52:16.525 WARN s:0/n:[100, 0, 0, 0, 0, 0, 0, 0, 253, 1]/ic_p2p/p2p P2P::process_messages(): processing msg_types = 1
Aug 28 14:52:16.525 ERRO s:0/n:[100, 0, 0, 0, 0, 0, 0, 0, 253, 1]/ic_messaging/xnet_endpoint No XNet configuration for node 5wjwg-gteaa-aaaaa-aaaap-2ai. This is an error in production, but may be ignored in single-subnet test deployments.
Aug 28 14:52:16.525 WARN s:0/n:[100, 0, 0, 0, 0, 0, 0, 0, 253, 1]/ic_p2p/p2p P2P::process_messages(): processing msg_types = 4
Aug 28 14:52:16.526 WARN s:0/n:[100, 0, 0, 0, 0, 0, 0, 0, 253, 1]/ic_p2p/⠒ Replica bound at 35489
replica address: "http://localhost:35489"
binding to: V4(127.0.0.1:8000)
  Internet Computer replica started...`

2. executing command `$dfx build` in another terminal
`sudo dfx build
Building canisters...
Build failed. Reason:
  Build step failed for canister 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q with error: Build failed. Reason:
  Command "/root/.cache/dfinity/versions/0.6.4/moc" "/home/dimas/motoko/examples/motoko/hello-world/src/main.mo" "-o" "/home/dimas/motoko/examples/motoko/hello-world/.dfx/local/canisters/hello-world/hello-world.did" "--idl" "--actor-idl" "/home/dimas/motoko/examples/motoko/hello-world/.dfx/local/canisters/idl/" "--actor-alias" "hello-world" "75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q" "--package" "base" "/root/.cache/dfinity/versions/0.6.4/base"
 returned an error:
/home/dimas/motoko/examples/motoko/hello-world/src/main.mo:5.5-5.12: type error, field printLn does not exist in type
  module {nyi : () -> None; unreachable : () -> None; xxx : () -> None}`

is there any that I missed?

**Comment by crusso** [comment]
Sorry, it seems that the examples have bit-rotted and need upgrading to 0.6.4. In particular, the printLn function has moved to another library. 

In the meantime, if you just type `dfx new hello`, it should create a sample hello world like project for you that should hopefully work.

**Comment by dimas-prawira** [comment]
Thanks @crusso, try with your suggestion 

1. running `$sudo dfx new hello`
`Fetching manifest https://sdk.dfinity.org/manifest.json
⠉ Checking for latest dfx version...
You seem to be running an outdated version of dfx.

You are strongly encouraged to upgrade by running 'dfx upgrade'!
Creating new project "hello"...
CREATE       hello/README.md (1.14KB)...
CREATE       hello/.gitignore (165B)...
CREATE       hello/dfx.json (582B)...
CREATE       hello/src/hello_assets/assets/sample-asset.txt (24B)...
CREATE       hello/src/hello/main.mo (107B)...
CREATE       hello/webpack.config.js (2.11KB)...
CREATE       hello/package.json (283B)...
CREATE       hello/src/hello_assets/public/index.js (137B)...
⠐ Installing node dependencies...
`

2. there is new folder created called `hello`, entering the folder and executing `$sudo dfx canister create hello`
`"hello" canister created with canister id: "cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q"`

3. executing `$sudo dfx build`
`sudo dfx build
Cannot find canister id.  Please issue 'dfx canister create hello_assets'.
`
4. executing `$dfx canister create hello_assets` based on suggestion
`"hello_assets" canister created with canister id: "7kncf-oidaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q"`

5. executing `$sudo dfx build`
`Building canisters...
Building frontend...`

6. executing `$sudo dfx canister call hello main`
`cannot find method type, dfx will send message with inferred type
Replica error (code 3): IC0302: Canister cxeji-wacaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q has no update method 'main'`

checking in the `src` folder there is already `main.mo` file. 

main.mo file content 

`actor {
    public func greet(name : Text) : async Text {
        return "Hello, " # name # "!";
    };
};
`
so I try executing `$sudo dfx canister call hello greet joe`

result 
`("Hello, joe!")`
