### ISSUE TITLE
Git submodule breaking on local for bitcoin dapp example

### ISSUE THREAD

**Issue by gabrielnic** [dfinity/examples#410]
Following the steps from here: https://internetcomputer.org/docs/current/developer-docs/integrations/bitcoin/local-development

At step 3 when I run `git submodule update --init --recursive`

I get: 

`gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin$ git submodule update --init --recursive
Submodule 'QR-Code-generator' (https://github.com/nayuki/QR-Code-generator) registered for path '../../c/qr/QR-Code-generator'
Submodule 'motoko/basic_bitcoin/motoko-bitcoin' (https://github.com/tgalal/motoko-bitcoin) registered for path 'motoko-bitcoin'
Submodule 'motoko/defi/DIP20' (https://github.com/Psychedelic/DIP20.git) registered for path '../defi/src/DIP20'
Submodule 'rust/defi/DIP20' (https://github.com/Psychedelic/DIP20.git) registered for path '../../rust/defi/src/DIP20'
Submodule 'svelte/svelte-motoko-starter/internet-identity' (https://github.com/dfinity/internet-identity.git) registered for path '../../svelte/svelte-motoko-starter/internet-identity'
Submodule 'svelte/svelte-starter/internet-identity' (https://github.com/dfinity/internet-identity.git) registered for path '../../svelte/svelte-starter/internet-identity'
Cloning into '/home/gabriel/projects/examples/c/qr/QR-Code-generator'...
Cloning into '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin'...
Cloning into '/home/gabriel/projects/examples/motoko/defi/src/DIP20'...
Cloning into '/home/gabriel/projects/examples/rust/defi/src/DIP20'...
Cloning into '/home/gabriel/projects/examples/svelte/svelte-motoko-starter/internet-identity'...
Cloning into '/home/gabriel/projects/examples/svelte/svelte-starter/internet-identity'...
Submodule path '../../c/qr/QR-Code-generator': checked out 'fd6917601d0a77b6b6df81599118212d8cdb9a27'
Submodule path 'motoko-bitcoin': checked out '39debbd377f03d861f33a99888f1162e51ef9a21'
Submodule 'motoko-sha' (git@github.com:tgalal/motoko-sha.git) registered for path 'motoko-bitcoin/motoko-sha'
Cloning into '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin/motoko-sha'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tgalal/motoko-sha.git' into submodule path '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin/motoko-sha' failed
Failed to clone 'motoko-sha'. Retry scheduled
Cloning into '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin/motoko-sha'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:tgalal/motoko-sha.git' into submodule path '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin/motoko-sha' failed
Failed to clone 'motoko-sha' a second time, aborting
Submodule path '../defi/src/DIP20': checked out '1d4b92781e46cee528e52f578c55e384561f380a'
Submodule path '../../rust/defi/src/DIP20': checked out 'cd365711ee4f34af9a6e74ca77d6637ee29d1755'
Submodule path '../../svelte/svelte-motoko-starter/internet-identity': checked out '58a63363b53b67f7d36c0002a3a0ab57dea4e4fb'
Submodule path '../../svelte/svelte-starter/internet-identity': checked out '58a63363b53b67f7d36c0002a3a0ab57dea4e4fb'
fatal: Failed to recurse into submodule path 'motoko-bitcoin'`

**Comment by manudrijvers** [comment]
Hi @gabrielnic, thanks for reporting this issue! 

Could you please try the following: `cd` into `examples/motoko/basic_bitcoin/motoko-bitcoin`,  and run `git submodule set-url motoko-sha https://github.com/tgalal/motoko-sha.git` there? Then you can go back to to `examples/motoko/basic_bitcoin` and re-run step 3 (`git submodule update --init --recursive`).

**Comment by gabrielnic** [comment]
Hi @manudrijvers 

I can confirm that worked 

`
gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin$ cd motoko-bitcoin/
gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin/motoko-bitcoin$ git submodule set-url motoko-sha https://github.com/tgalal/motoko-sha.git
Synchronising submodule url for 'motoko-sha'
gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin/motoko-bitcoin$ cd ..
gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin$ git submodule update --init --recursive
Cloning into '/home/gabriel/projects/examples/motoko/basic_bitcoin/motoko-bitcoin/motoko-sha'...
Submodule path 'motoko-bitcoin/motoko-sha': checked out 'a6d46445670407d51996c42892f696ed34d6296b'
gabriel@DESKTOP-8G906R5:~/projects/examples/motoko/basic_bitcoin$ 
` 

If someone can update the docs with this that would be great, Thank you

**Comment by manudrijvers** [comment]
Fantastic, thanks for confirming. Yes, it should be fixed for everybody with [this PR](https://github.com/dfinity/examples/pull/412).

**Comment by sesi200** [comment]
Closing as completed

**Comment by troublesprouter** [comment]
After this fix, this is now breaking: https://github.com/dfinity/examples/issues/413

I don't know if it's related or if it's breaking for another reason, but the example doesn't compile.
