### ISSUE TITLE
As a Developer, I want to know how to handle assets in the frontend so that I can modify my React app that way

### ISSUE THREAD

**Issue by JohannesKlauss** [dfinity/examples#45]
Currently it is extremely hard to port an existing web app with lazy loaded javascript and images to IC and there is no elaborate example to show how to do that.

I'd love to see an example that shows how to lazy load assets. I am thinking here wasm modules, workers, images, etc.
It begins with using a custom html file, which I managed to get by injecting it, but a CRA webpack built React project contains so many assets, that there needs to be a easy way to manage them (also considering the fact, that via HMR development, the assets have to work in a normal browser env as well).

I tried several ways, but i.e. an CRA bootstrapped app doesn't seem to be portable to the IC right now without a lot of effort. A guideline on how to do this would be a major enabler for web devs.

**Comment by lsgunnlsgunn** [comment]
Thanks for submitting this enhancement request. This is an important topic that we do want to cover. We'll put this issue in the enhancement queue and start providing information about how to do this as soon as we have useful information to pass along.
