### ISSUE TITLE
Compiling WASM with C/C++

### ISSUE THREAD

**Issue by skilesare** [dfinity/examples#48]
Could we get an update or some more examples for the C example?  For example, I'm trying to do the reverse example.
I start with a blank debian instance from docker. (I'll try to keep this list running and up to date for refference.

```
docker pull debian
docker run -ti debian
```

I run 

`apt-get install clang lld gcc-multilib`

and I get a bunch of not found errors.  A little research leads me to find that I need to run 

`apt-get update`

Great so I do that and the install command works.

I run the alias commands and they register fine, but they won't run.

I don't have code because I'm in a docker container so:

```
apt-get install git
cd usr
cd src
git clone https://github.com/dfinity/examples.git
cd examples
cd c
cd reverse
```

now I run 

`wcc reverse.c`

and get
```

reverse.c:16:19: warning: unknown attribute 'import_name' ignored [-Wunknown-attributes]
int dfn_ads(void) WASM_IMPORT("ic0", "msg_arg_data_size");
                  ^
reverse.c:13:75: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                                                          ^
reverse.c:16:19: warning: unknown attribute 'import_module' ignored [-Wunknown-attributes]
reverse.c:13:41: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                        ^
reverse.c:17:32: warning: unknown attribute 'import_name' ignored [-Wunknown-attributes]
void dfn_adc(void *, int, int) WASM_IMPORT("ic0", "msg_arg_data_copy");
                               ^
reverse.c:13:75: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                                                          ^
reverse.c:17:32: warning: unknown attribute 'import_module' ignored [-Wunknown-attributes]
reverse.c:13:41: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                        ^
reverse.c:18:36: warning: unknown attribute 'import_name' ignored [-Wunknown-attributes]
void dfn_reply_append(void *, int) WASM_IMPORT("ic0", "msg_reply_data_append");
                                   ^
reverse.c:13:75: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                                                          ^
reverse.c:18:36: warning: unknown attribute 'import_module' ignored [-Wunknown-attributes]
reverse.c:13:41: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                        ^
reverse.c:19:22: warning: unknown attribute 'import_name' ignored [-Wunknown-attributes]
void dfn_reply(void) WASM_IMPORT("ic0", "msg_reply");
                     ^
reverse.c:13:75: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                                                          ^
reverse.c:19:22: warning: unknown attribute 'import_module' ignored [-Wunknown-attributes]
reverse.c:13:41: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                        ^
reverse.c:20:29: warning: unknown attribute 'import_name' ignored [-Wunknown-attributes]
void dfn_print(void *, int) WASM_IMPORT("ic0", "debug_print");
                            ^
reverse.c:13:75: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
                                                                          ^
reverse.c:20:29: warning: unknown attribute 'import_module' ignored [-Wunknown-attributes]
reverse.c:13:41: note: expanded from macro 'WASM_IMPORT'
#define WASM_IMPORT(m,n) __attribute__((import_module(m))) __attribute__((import_name(n)));
```

I'm guessing this is ok since they are all warnings.

when I run 

`wld reverse.o -o reverse.wasm`

I get bash: wasm-ld-8: command not found.

Ok..so some investigation.  In /usr/bin/ I have wasm-ld-7?  Maybe I'll try:

alias wld="wasm-ld-7 --no-entry --export-dynamic --allow-undefined"

but that gets me wasm-ld-7: error: unknown argument: --export-dynamic

I'm guessing I need a newer version of wasm-ld? I google around a bit and find https://apt.llvm.org/ which gives me a script to run that includes wget. So

```
apt-get install wget
apt install lsb-release wget software-properties-common
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
```

Now I see wasm-ld-11 in my bin, but no 8.  Lets give it a try anyway.

```
alias wld="wasm-ld-11 --no-entry --export-dynamic --allow-undefined"
wld reverse.o -o reverse.wasm
```

And I'm stuck here:  wasm-ld-11: error: reverse.o: Unexpected metadata version: 1 (Expected: 2)

I'm not finding much info on the structure of the meta data or how to update it. I'm guessing it is the args in the reverse.c file, but I don't have much to go on for how to fix it.

**Comment by ggreif** [comment]
What is `wcc` spelled out? Try using `clang-11` with it. It is a good idea to use the newest toolchain (consistently!) when it comes to Wasm.

**Comment by skilesare** [comment]
alias wcc="clang --target=wasm32 -c -O3"

It would be great to know what -O3 means.  

I tried running this again after installing clang-11 but still got the unexpected metadata version.  I had to change wcc to

alias wcc="clang-11 --target=wasm32 -c -O3"

then

wcc reverse.c

compiled with no errors!

And 

alias wld="wasm-ld-11 --no-entry --export-dynamic --allow-undefined"
wld reverse.o -o reverse.wasm

works!

I'll keep pushing forward to see if dfx works and when it does I'll try to produce a docker file that other can use to get to this point.

**Comment by skilesare** [comment]
Ok...so I pushed forward and ran with the example:

`$ echo '{"canisters":{"reverse":{"main":"reverse"}}}' > dfx.json
$ mkdir build
$ mkdir build/reverse
$ cp reverse.wasm build/reverse/
$ head -c 8 /dev/urandom > build/reverse/_canister.id`

This all worked and now I have _canister.id file in /build/reverse that has a small bit of text in it 'DJZ~bq'. Does this look right?  I have no idea what head -c 8 /dev/urandom > build/reverse/_canister.id` actually does, but it seems that it runs a random number generator and puts the result in a file.

The first time I ran dfx canister install --all I got the following:

Cannot find canister id.  Please issue 'dfx canister create reverse'.

So I ran dfx canister create reverse and got a canniser with an ID of 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q then tried again.

I'm thinking that maybe the way canister IDs are handled has changed since the instructions were written? Because this is what I get now when I run dfx canister install --all:

xfx canister install --all
Installing code for canister reverse, with canister_id 75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q
An error occured:
Io(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)

Looks like maybe a rust error?  I do have nodejs installed and dfx installed.  Any ideas? Maybe the dfx.json file structure has changed as well?

**Comment by skilesare** [comment]
I also tried echo "75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q" > _canister.id incase it was the id issue.  Didn't work.

**Comment by ggreif** [comment]
Do you have the `dfx build` products under `find .dfx/local/canisters`?

**Comment by ggreif** [comment]
> I also tried echo "75hes-oqbaa-aaaaa-aaaaa-aaaaa-aaaaa-aaaaa-q" > _canister.id incase it was the id issue. Didn't work.

No way this will work. These examples were created using an ancient version of the SDK, so I expect that a lot has changed from the ad-hoc way we did it back then. Please use the newest `dfx` from `sdk.dfinity.org`.

**Comment by chenyan2002** [comment]
`dfx.json` is very old. The following should work:

```
{
  "canisters": {
    "reverse": {
      "type": "custom",
      "wasm": "reverse.wasm",
      "candid": "reverse.did"
    }
  }
}
```
wasm and candid key is the location of your wasm and did files.

reverse.did
```
service : {
  reverse: (text) -> (text);
}
```

Then you can run `dfx build` and `dfx canister install --all`

**Comment by skilesare** [comment]
I got it working and submitted a pull request:

https://github.com/dfinity/examples/pull/49
