### ISSUE TITLE
Error: Cannot find canister id. Please issue 'dfx canister create dbank'.

### ISSUE THREAD

**Issue by navalega0109** [dfinity/examples#589]
Hi I'm able to deploy dfx successfully but getting below error while calling public func from of class from dbank app.

Check the below image for more information.

![issue](https://github.com/dfinity/examples/assets/116286227/837f07a6-f0ef-4826-9f1e-eab3079c1271)

**Comment by sesi200** [comment]
Your project contains the two canisters `dbank_backend` and `dbank_frontend`. There is no canister called `dbank`. I suspect you want to call it like this: `dfx canister call dbank_backend topUp`

**Comment by navalega0109** [comment]
@sesi200 You're right!!! The tutorial I was taking that user was working on old version of dfx as result canister created for him was different than mine. I realized that yesterday! Thanks for help :)
