### ISSUE TITLE
use of update methods

### ISSUE THREAD

**Issue by mzurs** [dfinity/examples#619]
Is there any specific reason for the use of update methods in all Bitcoin API getters rather than designating them as query methods?

https://github.com/dfinity/examples/blob/baa611185e2b118955419b22abafee058f4e916b/rust/basic_bitcoin/src/basic_bitcoin/src/lib.rs#L42

**Comment by adamspofford-dfinity** [comment]
All functions that make inter-canister calls must be update functions.
