### ISSUE TITLE
NFT minting is missing the canisister id in the example.  Breadcrumbsportal/docs/samples /nft.md

### ISSUE THREAD

**Issue by testpuddle** [dfinity/examples#733]
The step to deploy fails.  It needs the canister id as the last argument:   

dfx deploy --no-wallet --argument \
"(record {
    name = \"Numbers One Through Fifty\";
    symbol = \"NOTF\";
    logo = opt record {
        data = \"$(base64 -i ./logo.png)\";
        logo_type = \"image/png\";
    };
    custodians = opt vec { principal \"$(dfx identity get-principal)\" };
})"  dip721_nft_container            <<<<<<<<<<<<----- the canister name is required.  Works when I added dip721_nft_container [I think].

**Comment by jessiemongeon1** [comment]
This edit must be done in the Examples repo, as the documentation pages are pulled from there. I am transferring this issue to the Examples repo.
