### ISSUE TITLE
Unknown version '0.7.0-beta.6' - Mac.

### ISSUE THREAD

**Issue by MustafaAnasKH99** [dfinity/examples#84]
running any dfx command inside any example directory throws this error:
```
Warning: The version of DFX used (0.7.0-beta.6) is different than the version being run (0.6.26).
This might happen because your dfx.json specifies an older version, or DFX_VERSION is set in your environment.
We are forwarding the command line to the old version. To disable this warning, set the DFX_WARNING=-version_check environment variable.

Error when trying to forward to project dfx:
Unknown version '0.7.0-beta.6'.
Installed executable: 0.6.26
```

Is there a command line to downgrade to a different version of the SDK?

**Comment by flauc** [comment]
I'm getting the same issue on ubuntu. I think '0.7.0' might only be released internally, '0.6.26' seems to be the latest available version at the moment.

**Comment by adeoluwa-adebiyi** [comment]
Experiencing the same on Mac. How do we downgrade to the supported '0.6.26' version. Than

**Comment by dfx-json** [comment]
Resolved by dfxvm
