### ISSUE TITLE
SDK Update

### ISSUE THREAD

**Issue by fury02** [dfinity/examples#93]
**How do I get the seventh version?
Default install command sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)" instaled version "latest": "0.6.26". 
Examples are presented in the updated version

API
https://sdk.dfinity.org/manifest.json

{
    "tags": {
        "latest": "0.6.26"
    },
    "versions": [
        "0.5.0",
        "0.5.2",
        "0.5.3",
        "0.5.4",
        "0.5.5",
        "0.5.6",
        "0.5.7",
        "0.5.8",
        "0.5.11",
        "0.5.15",
        "0.6.0",
        "0.6.1",
        "0.6.2",
        "0.6.3",
        "0.6.4",
        "0.6.6",
        "0.6.7",
        "0.6.9",
        "0.6.10",
        "0.6.11",
        "0.6.12",
        "0.6.13",
        "0.6.14",
        "0.6.16",
        "0.6.17",
        "0.6.18",
        "0.6.20",
        "0.6.21",
        "0.6.22",
        "0.6.23",
        "0.6.24",
        "0.6.25",
        "0.6.26",
        "0.7.0-beta.0",
        "0.7.0-beta.1",
        "0.7.0-beta.2",
        "0.7.0-beta.3",
        "0.7.0-beta.4",
        "0.7.0-beta.5",
        "0.7.0-beta.6",
        "0.7.0-beta.7",
        "0.7.0-beta.8",
        "0.7.0"
    ]
}

**Comment by lsgunnlsgunn** [comment]
@fury02 You can use the DFX_VERSION=0.7.0 environment variable in front of the install command. 
This is documented in the Install, upgrade, and remove software section of the documentation (and other places).

**Comment by lsgunnlsgunn** [comment]
https://sdk.dfinity.org/docs/developers-guide/install-upgrade-remove.html#install-version

**Comment by lsgunnlsgunn** [comment]
https://sdk.dfinity.org/docs/developers-guide/install-upgrade-remove.html#install-version

**Comment by der0pa** [comment]
DFX_VERSION=0.7.1 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

seems to work
