### ISSUE TITLE
Motoko basic_bitcoin: Bitcoin canister not found locally

### ISSUE THREAD

**Issue by jessiemongeon1** [dfinity/examples#989]
Fails to find BTC canister locally; fails to use correct signing key locally.

**Comment by dsarlis** [comment]
@jessiemongeon1 I'm not sure the example is set up to work locally. The README also suggests to use mainnet. Is it a requirement that examples should also work locally?

**Comment by jessiemongeon1** [comment]
That's fine as long as that is the expected behavior. I'll update the README with a clear statement that this example intentionally does not work locally.
