### ISSUE TITLE
Motoko encrypted-notes-dapp-vetkd: Does not deploy

### ISSUE THREAD

**Issue by jessiemongeon1** [dfinity/examples#990]
Does not deploy due to cannot resolve file paths

**Comment by fspreiss** [comment]
@jessiemongeon1, thanks for the report! can you elaborate what you mean with "old URLs"? What error do you see? I just tried to compile and deploy and run the dapp for both build environments (`export BUILD_ENV=rust` and `export BUILD_ENV=motoko`), and it worked for both, using `dfx 0.23.0`.

**Comment by jessiemongeon1** [comment]
@fspreiss by URLs I mean file paths (I should have been clearer in the initial issue), I get the following error when trying to deploy:

```[!] Error: Could not resolve '../../../declarations/encrypted_notes_motoko/encrypted_notes_motoko.did.js' from src/frontend/src/lib/backend.ts
```

**Comment by fspreiss** [comment]
@jessiemongeon1, which steps are you performing before you arrive at this error? Are you following the instructions of the README? At which step do you see the mentioned error? Note that the deployment instructions of the README are to a big part automated in the [Makefile](https://github.com/dfinity/examples/blob/master/motoko/encrypted-notes-dapp-vetkd/Makefile) in the `test-e2e` target, so you could first try `make clean` to clean your environment, and then `make test-e2e`.

**Comment by fspreiss** [comment]
@jessiemongeon1, also note that the file you are seemingly missing is generated in Step 10 of the instructions in the [README](https://github.com/dfinity/examples/blob/master/motoko/encrypted-notes-dapp-vetkd/README.md). Step 10 says: `dfx generate "encrypted_notes_$BUILD_ENV"`: possibly you didn't have a `BUILD_ENV` set (see [Step1](https://github.com/dfinity/examples/blob/master/motoko/encrypted-notes-dapp-vetkd/README.md#step-1-choose-which-implementation-to-use-by-setting-a-respective-environment-variable) of the instructions), which could have caused Step10 to fail.

**Comment by jessiemongeon1** [comment]
Yes, I followed the instructions in the README and set the `BUILD_ENV` variable as the README says. Running `make clean` and `make test-e2e` seems to have resolved the issue. Thanks!

**Comment by fspreiss** [comment]
Happy to hear! Let me know if you think we should adapt the README to recommend running, e.g., `make clean` at the beginning (e.g., if people face deployment issues).
