### ISSUE TITLE
Motoko vetkd: Frontend canister fails to deploy

### ISSUE THREAD

**Issue by jessiemongeon1** [dfinity/examples#994]
Frontend canister fails to compile and deploy.

**Comment by fspreiss** [comment]
@jessiemongeon1, can you describe the error you see. I just tried to compile and deploy the dapp, and for me it worked, using `dfx 0.23.0`.

In any case, when using the dapp, I found issues with the II integration that I'm currently analyzing, but I believe these were not the issues you meant with this ticket.
